version: '3.8'

services:
  app:
    build: .
    container_name: nest-app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://docker:docker@db:5432/brain
    command: >
      sh -c "
      npm install &&
      npm run build &&
      npx prisma generate &&
      npx prisma migrate deploy &&
      node dist/main.js
      "

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: brain
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
