version: '3.8'

services:
 
  #app:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile.dev
  #  container_name: nest-app
  #  ports:
  #    - '3000:3000'
  #  volumes:
  #    - .:/app
  #    - /app/node_modules
  #  depends_on:
  #    - db
  #  environment:
  #    DATABASE_URL: postgresql://docker:docker@db:5432/brain
    #command: >
    #  sh -c "
    #  npx prisma generate &&
    #  npm run start:dev
    #  "
   
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: brain
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
